windowrulev2 = float, class:^(randy)$
#windowrulev2 = persistentsize, class:^(randy)$

# those are pixel values for my 1080p setup
windowrulev2 = move 1530 55, class:^(randy)$

windowrulev2 = nofocus, class:^(randy)$
windowrulev2 = nodim, class:^(randy)$
windowrulev2 = noshadow, class:^(randy)$
windowrulev2 = noborder, class:^(randy)$
windowrulev2 = opacity, 1 override 1 override 1 override, class:^(randy)$
windowrulev2 = workspace 2,class:^(randy)$
